apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointslices-access
rules:
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-endpointslices-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: endpointslices-access
subjects:
- kind: ServiceAccount
  name: nginx-ingress
  namespace: nginx-ingress
