apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nginx-ingress
  name: lease-access
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-ingress-lease-access
  namespace: nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lease-access
subjects:
- kind: ServiceAccount
  name: nginx-ingress
  namespace: nginx-ingress
